### ISSUE TITLE
[xUnit] [ERROR] - Conversion error Error to convert the input XML document

### ISSUE THREAD

**Issue by xJom** [shawnliang/cunit-to-junit#1]
Fails to compile the stylesheet, using CUnit 2.1, Jenkins 1.596.2, Java 8u31.

Error log as follows:

ERROR: Publisher org.jenkinsci.plugins.xunit.XUnitPublisher aborted due to exception
java.io.IOException: remote file operation failed: C:\Jenkins_slave\workspace\Elvira_UnitTest at hudson.remoting.Channel@12355027:RT_VM_af_b0b4b4j: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
    at hudson.FilePath.act(FilePath.java:977)
    at hudson.FilePath.act(FilePath.java:959)
    at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:138)
    at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:81)
    at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:112)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
    at hudson.model.Run.execute(Run.java:1784)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Caused by: hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:181)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:42)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2677)
    at hudson.remoting.UserRequest.perform(UserRequest.java:121)
    at hudson.remoting.UserRequest.perform(UserRequest.java:49)
    at hudson.remoting.Request$2.run(Request.java:324)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at hudson.remoting.Engine$1$1.run(Engine.java:63)
    at java.lang.Thread.run(Unknown Source)
    at ......remote call to RT_VM_af_b0b4b4j(Native Method)
    at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1356)
    at hudson.remoting.UserResponse.retrieve(UserRequest.java:221)
    at hudson.remoting.Channel.call(Channel.java:752)
    at hudson.FilePath.act(FilePath.java:970)
    ... 13 more
Caused by: org.jenkinsci.plugins.xunit.exception.XUnitException: Conversion error Error to convert the input XML document
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convert(XUnitConversionService.java:87)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:144)
    at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:42)
    at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2677)
    at hudson.remoting.UserRequest.perform(UserRequest.java:121)
    at hudson.remoting.UserRequest.perform(UserRequest.java:49)
    at hudson.remoting.Request$2.run(Request.java:324)
    at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at hudson.remoting.Engine$1$1.run(Engine.java:63)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.jenkinsci.lib.dtkit.util.converter.ConversionException: Error to convert the input XML document
    at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:356)
    at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:172)
    at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:111)
    at org.jenkinsci.lib.dtkit.model.InputMetricXSL.convert(InputMetricXSL.java:183)
    at org.jenkinsci.lib.dtkit.model.InputMetricXSL.convert(InputMetricXSL.java:189)
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convertCustomInputMetric(XUnitConversionService.java:98)
    at org.jenkinsci.plugins.xunit.service.XUnitConversionService.convert(XUnitConversionService.java:76)
    ... 12 more
Caused by: net.sf.saxon.s9api.SaxonApiException: Failed to compile stylesheet. 1 error detected.
    at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:149)
    at org.jenkinsci.lib.dtkit.util.converter.ConversionService.convert(ConversionService.java:324)
    ... 18 more
Caused by: javax.xml.transform.TransformerConfigurationException: Failed to compile stylesheet. 1 error detected.
    at net.sf.saxon.PreparedStylesheet.prepare(PreparedStylesheet.java:176)
    at net.sf.saxon.PreparedStylesheet.compile(PreparedStylesheet.java:79)
    at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:146)

**Comment by xJom** [comment]
And also, in the error.log, I found that:

Error on line 32 column 71 
  SXXP0003: Error reported by XML parser: Attribute name "data-pjax-transient" associated
  with an element type "meta" must be followed by the ' = ' character.

**Comment by xJom** [comment]
Somehow, the download from GitHub went wrong, same issue as in Ranorex-converter: http://www.ranorex.com/blog/make-your-ranorex-report-fully-comprehensible-for-jenkins-by-using-xunit
